make it fail if it fails

diff --git a/.github/workflows/build_rPackages.yaml b/.github/workflows/build_rPackages.yaml
--- a/.github/workflows/build_rPackages.yaml
+++ b/.github/workflows/build_rPackages.yaml
@@ -36,18 +36,10 @@ jobs:
       - name: Build on date ${{ github.event.client_payload.ref_name }} (default1.nix)
         run: |
           nix-build --max-jobs 1 --cores 2 default1.nix --keep-going 2>&1 | tee -a build-linux.log
-          if [ $? -ne 0 ]; then
-            echo "nix-build failed to build one or more dependencies."
-            exit 1
-          fi
 
       - name: Build on date ${{ github.event.client_payload.ref_name }} (default2.nix)
         run: |
           nix-build --max-jobs 1 --cores 2 default2.nix --keep-going 2>&1 | tee -a build-linux.log
-          if [ $? -ne 0 ]; then
-            echo "nix-build failed to build one or more dependencies."
-            exit 1
-          fi
 
       - name: Upload build log
         uses: actions/upload-artifact@v4
@@ -55,6 +47,18 @@ jobs:
           name: build-linux-log
           path: build-linux.log
         continue-on-error: true
+
+      - name: Check for failed builds
+        run: |
+          # Extract failed packages
+          grep -oE 'removing.*' build-linux.log | sort -u > failed.txt
+          if [ -s failed.txt ]; then
+            echo "Some packages failed to build:"
+            cat failed.txt
+            exit 1
+          else
+            echo "All packages built successfully."
+          fi
 
   build-on-macos:
     runs-on: macos-latest
@@ -80,19 +84,11 @@ jobs:
 
       - name: Build on date ${{ github.event.client_payload.ref_name }} (default1.nix)
         run: |
-          nix-build --max-jobs 1 --cores 2 default1.nix --keep-going 2>&1 | tee -a build-linux.log
-          if [ $? -ne 0 ]; then
-            echo "nix-build failed to build one or more dependencies."
-            exit 1
-          fi
+          nix-build --max-jobs 1 --cores 2 default1.nix --keep-going 2>&1 | tee -a build-darwin.log
 
       - name: Build on date ${{ github.event.client_payload.ref_name }} (default2.nix)
         run: |
-          nix-build --max-jobs 1 --cores 2 default2.nix --keep-going 2>&1 | tee -a build-linux.log
-          if [ $? -ne 0 ]; then
-            echo "nix-build failed to build one or more dependencies."
-            exit 1
-          fi
+          nix-build --max-jobs 1 --cores 2 default2.nix --keep-going 2>&1 | tee -a build-darwin.log
 
       - name: Upload build log
         uses: actions/upload-artifact@v4
@@ -100,6 +96,18 @@ jobs:
           name: build-darwin-log
           path: build-darwin.log
         continue-on-error: true
+
+      - name: Check for failed builds
+        run: |
+          # Extract failed packages
+          grep -oE 'removing.*' build-darwin.log | sort -u > failed.txt
+          if [ -s failed.txt ]; then
+            echo "Some packages failed to build:"
+            cat failed.txt
+            exit 1
+          else
+            echo "All packages built successfully."
+          fi
 
 #  clone-and-open-pr:
 #      name: Clone rix and open PR
